// <auto-generated />
namespace ProjectF2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix14));
        
        string IMigrationMetadata.Id
        {
            get { return "201607262155402_fix14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
