// <auto-generated />
namespace ProjectF2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MarcaeModelofk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MarcaeModelofk));
        
        string IMigrationMetadata.Id
        {
            get { return "201607232201301_Marca-e-Modelo-fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
